#ifndef EXCHANGE_SIGNALS_GLOBAL_H
#define EXCHANGE_SIGNALS_GLOBAL_H

//#include <QtCore/qglobal.h>

#if defined(EXCHANGE_SIGNALS_LIBRARY)
#  define EXCHANGE_SIGNALS_EXPORT Q_DECL_EXPORT
#else
#  define EXCHANGE_SIGNALS_EXPORT Q_DECL_IMPORT
#endif

#endif // EXCHANGE_SIGNALS_GLOBAL_H
